# Generated by Django 5.0 on 2023-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='king',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
